"""
Launcher script for the packaged Claude Code Role Play application.

This is the entry point for the PyInstaller bundle. It:
1. Sets up paths for bundled resources
2. Runs first-time setup wizard if needed (console mode only)
3. Starts the uvicorn server

When run as a Tauri sidecar:
- Setup is handled by Tauri's GUI wizard
- Browser is not opened (Tauri provides the webview)
- Graceful shutdown on SIGTERM
"""

import getpass
import os
import secrets
import signal
import sys
from pathlib import Path


def get_base_path() -> Path:
    """Get the base path for resources (handles both dev and bundled modes)."""
    if getattr(sys, "frozen", False):
        # Running as PyInstaller bundle
        return Path(sys._MEIPASS)
    else:
        # Running in development
        return Path(__file__).parent.parent


def get_work_dir() -> Path:
    """Get the working directory for user data (.env, agents, etc.)."""
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    else:
        return Path(__file__).parent.parent


def setup_paths():
    """Set up Python paths for imports."""
    base_path = get_base_path()

    # Add backend to Python path
    backend_path = base_path / "backend"
    if backend_path.exists():
        sys.path.insert(0, str(backend_path))
    else:
        # In dev mode, backend is current directory's parent
        sys.path.insert(0, str(Path(__file__).parent))

    # Set working directory
    work_dir = get_work_dir()
    os.chdir(work_dir)


def copy_default_agents():
    """Copy default agents if they don't exist."""
    if not getattr(sys, "frozen", False):
        return

    base_path = get_base_path()
    work_dir = get_work_dir()

    agents_dest = work_dir / "agents"
    agents_src = base_path / "agents"
    if not agents_dest.exists() and agents_src.exists():
        import shutil

        shutil.copytree(agents_src, agents_dest)
        print(f"기본 에이전트를 복사했습니다: {agents_dest}")


def is_env_configured(env_file: Path) -> bool:
    """Check if .env file has valid configuration."""
    if not env_file.exists():
        return False

    content = env_file.read_text(encoding="utf-8")

    # Check for placeholder values that indicate unconfigured state
    has_valid_hash = "API_KEY_HASH=" in content and "example_hash" not in content and "paste_your" not in content
    has_valid_jwt = "JWT_SECRET=" in content and "your-random-secret" not in content

    return has_valid_hash and has_valid_jwt


def run_first_time_setup():
    """Run interactive first-time setup wizard."""
    import bcrypt

    print("=" * 60)
    print("Claude Code Role Play - 초기 설정")
    print("=" * 60)
    print()
    print("환영합니다! 애플리케이션을 설정해주세요.")
    print()

    # Get password from user
    while True:
        password = getpass.getpass("비밀번호를 입력하세요: ")
        if len(password) < 4:
            print("비밀번호는 최소 4자 이상이어야 합니다. 다시 시도해주세요.")
            continue

        password_confirm = getpass.getpass("비밀번호 확인: ")
        if password != password_confirm:
            print("비밀번호가 일치하지 않습니다. 다시 시도해주세요.")
            continue

        if len(password) < 8:
            print("\n참고: 비밀번호가 8자 미만입니다.")
            proceed = input("계속하시겠습니까? (Y/n): ").strip().lower()
            if proceed == "n":
                continue

        break

    # Generate password hash
    salt = bcrypt.gensalt()
    password_hash = bcrypt.hashpw(password.encode("utf-8"), salt).decode("utf-8")

    # Generate JWT secret
    jwt_secret = secrets.token_hex(32)

    # Get user name (optional)
    user_name = input("\n표시할 이름을 입력하세요 (기본값: User): ").strip()
    if not user_name:
        user_name = "User"

    return {
        "password_hash": password_hash,
        "jwt_secret": jwt_secret,
        "user_name": user_name,
    }


def create_env_file(env_file: Path, config: dict):
    """Create .env file with user configuration."""
    env_content = f"""USER_NAME={config["user_name"]}
CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK=true

# Authentication (auto-generated by setup wizard)
API_KEY_HASH={config["password_hash"]}

# JWT Secret (auto-generated)
JWT_SECRET={config["jwt_secret"]}

# Set to "true" for debug logging
DEBUG_AGENTS=false
"""

    env_file.write_text(env_content, encoding="utf-8")
    print(f"\n설정이 저장되었습니다: {env_file}")


def setup_environment() -> bool:
    """Set up environment for the bundled application. Returns True if setup was run."""
    work_dir = get_work_dir()
    env_file = work_dir / ".env"

    # Copy default agents
    copy_default_agents()

    # Check if setup is needed
    if is_env_configured(env_file):
        return False

    # Run first-time setup
    try:
        config = run_first_time_setup()
        create_env_file(env_file, config)
        print()
        print("=" * 60)
        print("설정 완료! 애플리케이션을 시작합니다...")
        print("=" * 60)
        print()
        return True
    except KeyboardInterrupt:
        print("\n\n설정이 취소되었습니다.")
        sys.exit(0)


def is_tauri_sidecar() -> bool:
    """Check if running as a Tauri sidecar."""
    # Tauri sets this when spawning sidecars, or check parent process
    return os.environ.get("TAURI_SIDECAR") == "1" or "--sidecar" in sys.argv


def run_mcp_server(server_type: str) -> None:
    """Run in MCP server mode (for self-spawn from bundled exe).

    This is called when the exe is invoked with --mcp-server argument,
    allowing Codex to spawn this exe as an MCP server subprocess.

    Args:
        server_type: Either "action" or "guidelines"
    """
    import asyncio

    # Set up paths for imports
    setup_paths()

    if server_type == "action":
        from mcp_servers.action_server import main as server_main
    elif server_type == "guidelines":
        from mcp_servers.guidelines_server import main as server_main
    else:
        print(f"Unknown MCP server type: {server_type}", file=sys.stderr)
        print("Valid types: action, guidelines", file=sys.stderr)
        sys.exit(1)

    # Run the MCP server (async main)
    asyncio.run(server_main())


def main():
    """Main entry point."""
    # Check for MCP server mode first (before any other setup)
    # This allows the bundled exe to be spawned as an MCP server subprocess
    if "--mcp-server" in sys.argv:
        try:
            idx = sys.argv.index("--mcp-server")
            server_type = sys.argv[idx + 1]
        except (IndexError, ValueError):
            print("Usage: ClaudeCodeRP.exe --mcp-server <action|guidelines>", file=sys.stderr)
            sys.exit(1)
        run_mcp_server(server_type)
        return  # MCP server handles its own exit

    # Set up paths first
    setup_paths()

    # Set up signal handlers for graceful shutdown
    def signal_handler(signum, frame):
        print("\n서버를 종료합니다...")
        sys.exit(0)

    signal.signal(signal.SIGTERM, signal_handler)
    signal.signal(signal.SIGINT, signal_handler)

    # Check if running as Tauri sidecar
    sidecar_mode = is_tauri_sidecar()

    # Run environment setup (including first-time wizard if needed)
    # In sidecar mode, Tauri handles setup via GUI
    if not sidecar_mode:
        setup_environment()

    # Import uvicorn and app after setting up paths
    import uvicorn

    print("=" * 60)
    print("Claude Code Role Play")
    print("=" * 60)
    print()
    print("서버 시작 중: http://localhost:8000")
    if not sidecar_mode:
        print("서버를 중지하려면 Ctrl+C를 누르세요")
    print()

    # Import the app directly instead of using string path
    # This works better with PyInstaller bundling
    from main import app

    # Run the server with the app object directly
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info",
    )


if __name__ == "__main__":
    main()
