"""
Shared MCP Image Server for ChitChats.

This server exposes the image generation tool (draw) via the MCP protocol.
It can be used by any AI provider (Claude SDK, Codex CLI, etc.).

The picture is generated by the Codex backend's /images/generations endpoint,
authenticated with the ChatGPT OAuth tokens in ~/.codex/auth.json. That auth is
independent of which provider is driving the agent, so Claude rooms can draw too
as long as `codex login` has been run.

This replaces Codex's built-in image_generation feature (turned off in
providers/configs.py), which offered no control over the tool description and no
way to feed a character's registered appearance into the prompt.

Usage:
    # Factory mode (in-process)
    from mcp_servers import create_image_server
    server = create_image_server(agent_name="TestAgent", provider="claude")

    # Subprocess mode (stdio)
    AGENT_NAME=TestAgent python -m mcp_servers.image_server

Environment variables (for subprocess mode):
    AGENT_NAME: Name of the agent (required)
    AGENT_GROUP: Group name for tool config overrides (optional)
    CONFIG_FILE: Path to agent config folder (optional, for the agent's own appearance)
    PROVIDER: AI provider (optional, default: claude)
"""

import json
import os
import subprocess
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional

from mcp.server import Server
from mcp.types import TextContent

from .base import build_server, run_stdio, setup_logging
from .config import get_tool_response

logger = setup_logging("ImageServer")

# Codex backend image endpoint, and the OAuth tokens it authenticates with.
BASE_URL = "https://chatgpt.com/backend-api/codex"
AUTH_PATH = Path.home() / ".codex" / "auth.json"

MODEL = "gpt-image-2"
REQUEST_TIMEOUT = 300

# The backend rejects clients it doesn't recognise, so requests claim the installed
# codex-cli version. Used only when the CLI can't be asked directly.
FALLBACK_CLIENT_VERSION = "0.144.3"

_client_version: Optional[str] = None


def create_image_server(
    agent_name: str,
    group_name: Optional[str] = None,
    config_file: Optional[str] = None,
    provider: str = "claude",
) -> Server:
    """
    Create an MCP server with the image generation tool (draw).

    Args:
        agent_name: Name of the agent
        group_name: Optional group name for tool config overrides
        config_file: Path to the agent's config folder (for its own appearance)
        provider: AI provider ("claude" or "codex")

    Returns:
        Configured MCP Server instance
    """
    return build_server(
        "chitchats_image",
        "image",
        handlers={"draw": _handle_draw},
        context={
            "agent_name": agent_name,
            "agent_group": group_name,
            "config_file": config_file,
            "provider": provider,
        },
    )


# =============================================================================
# Tool Handlers
# =============================================================================


def _handle_draw(_name: str, arguments: dict, context: dict) -> list[TextContent]:
    """Handle draw tool call: build the prompt, generate, persist, return the URL."""
    prompt = (arguments.get("prompt") or "").strip()
    if not prompt:
        return [TextContent(type="text", text="Error: Prompt cannot be empty")]

    agent_name = context["agent_name"]

    if arguments.get("involve_appearance", True):
        cast = _resolve_cast(arguments.get("characters"), agent_name)
        prompt = _build_prompt(prompt, cast, context)

    logger.info(f"[draw] {agent_name}: {prompt[:120]}...")

    try:
        image_b64 = _generate_image(prompt)
    except Exception as e:
        logger.error(f"[draw] generation failed: {e}")
        return [TextContent(type="text", text=f"The picture could not be created: {e}")]

    from infrastructure.generated_images import save_generated_image

    saved = save_generated_image(image_b64, media_type="image/png")
    if saved is None:
        return [TextContent(type="text", text="The picture was created but could not be saved.")]

    url, _media_type = saved
    response_text = get_tool_response(
        "draw",
        group_name=context["agent_group"],
        agent_name=agent_name,
        image_url=url,
    )
    return [TextContent(type="text", text=response_text)]


# =============================================================================
# Prompt Building
# =============================================================================


def _resolve_cast(characters: Optional[list], agent_name: str) -> list[str]:
    """Decide which characters the picture describes.

    A picture with no named cast is a picture of the drawing agent; once names are
    given they are the cast exactly, so an agent can draw a scene it is not in.
    """
    if not characters:
        return [agent_name]

    names = [str(name).strip() for name in characters if str(name).strip()]
    return names or [agent_name]


def _build_prompt(prompt: str, cast: list[str], context: dict) -> str:
    """Prepend each character's registered appearance to the scene description."""
    blocks = []
    for name in cast:
        appearance = _appearance_for(name, context)
        if appearance:
            blocks.append(f"{name} looks like this:\n{appearance}")
        else:
            logger.info(f"[draw] no appearance on file for '{name}'")

    if not blocks:
        return prompt

    return "\n\n".join([*blocks, f"Scene to draw:\n{prompt}"])


def _appearance_for(name: str, context: dict) -> str:
    """Look up a character's appearance section from their agent folder."""
    try:
        from domain.agent_parser import get_appearance_by_folder, get_appearance_by_name

        # The caller's own folder is known exactly; others are found by name.
        config_file = context["config_file"]
        if name == context["agent_name"] and config_file:
            from core import AgentConfigService

            folder = AgentConfigService.get_project_root() / config_file
            appearance = get_appearance_by_folder(folder)
            if appearance:
                return appearance

        return get_appearance_by_name(name)
    except Exception as e:
        logger.warning(f"[draw] failed to load appearance for '{name}': {e}")
        return ""


# =============================================================================
# Image Generation
# =============================================================================


def _generate_image(prompt: str) -> str:
    """POST to the Codex image endpoint and return the base64-encoded PNG.

    Raises:
        RuntimeError: if the request is unauthenticated, rejected, or returns no image.
    """
    tokens = _load_tokens()
    version = _get_client_version()

    body = {
        "prompt": prompt,
        "model": MODEL,
        "quality": "auto",
        "size": "auto",
        "background": "auto",
    }
    request = urllib.request.Request(
        f"{BASE_URL}/images/generations",
        data=json.dumps(body).encode(),
        headers={
            "Authorization": f"Bearer {tokens['access_token']}",
            "ChatGPT-Account-ID": tokens["account_id"],
            "Content-Type": "application/json",
            "version": version,
            "originator": "codex_cli_rs",
            "User-Agent": f"codex_cli_rs/{version}",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:500]
        raise RuntimeError(f"image endpoint returned HTTP {e.code} {e.reason}: {detail}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"could not reach the image endpoint: {e.reason}") from e

    data = payload.get("data") or []
    if not data or not data[0].get("b64_json"):
        raise RuntimeError("the image endpoint returned no image")

    return data[0]["b64_json"]


def _load_tokens() -> dict:
    """Read the ChatGPT OAuth tokens written by `codex login`."""
    if not AUTH_PATH.exists():
        raise RuntimeError(f"not authenticated: {AUTH_PATH} is missing. Run `codex login`.")

    try:
        tokens = json.loads(AUTH_PATH.read_text())["tokens"]
    except (json.JSONDecodeError, KeyError) as e:
        raise RuntimeError(f"could not read credentials from {AUTH_PATH}: {e}") from e

    if not tokens.get("access_token") or not tokens.get("account_id"):
        raise RuntimeError(f"{AUTH_PATH} has no usable ChatGPT credentials. Run `codex login`.")

    return tokens


def _get_client_version() -> str:
    """Report the installed codex-cli version, asking the CLI once per process."""
    global _client_version

    if _client_version is not None:
        return _client_version

    _client_version = FALLBACK_CLIENT_VERSION
    try:
        result = subprocess.run(
            ["codex", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        # "codex-cli 0.144.3" -> "0.144.3"
        version = result.stdout.strip().split()[-1]
        if result.returncode == 0 and version:
            _client_version = version
    except Exception as e:
        logger.warning(f"[draw] could not detect codex version, using {FALLBACK_CLIENT_VERSION}: {e}")

    return _client_version


# =============================================================================
# Standalone Server Entry Point
# =============================================================================


def from_env(config: dict) -> Server:
    """Build the image server, reading the one env var only this server takes."""
    return create_image_server(
        agent_name=config["agent_name"],
        group_name=config["agent_group"],
        config_file=os.environ.get("CONFIG_FILE"),
        provider=config["provider"],
    )


if __name__ == "__main__":
    run_stdio("Image", from_env)
