"""Read/write the .env file used by the bundled app."""

from pathlib import Path


def is_env_configured(env_file: Path) -> bool:
    """Check if .env file has valid configuration."""
    if not env_file.exists():
        return False

    content = env_file.read_text(encoding="utf-8")

    has_valid_hash = "API_KEY_HASH=" in content and "example_hash" not in content and "paste_your" not in content
    has_valid_jwt = "JWT_SECRET=" in content and "your-random-secret" not in content

    return has_valid_hash and has_valid_jwt


def create_env_file(env_file: Path, config: dict):
    """Create .env file with user configuration."""
    env_content = f"""USER_NAME={config["user_name"]}
CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK=true

# Authentication (auto-generated by setup wizard)
API_KEY_HASH={config["password_hash"]}

# JWT Secret (auto-generated)
JWT_SECRET={config["jwt_secret"]}

# Set to "true" for debug logging
DEBUG_AGENTS=false
"""

    env_file.write_text(env_content, encoding="utf-8")
    print(f"\n설정이 저장되었습니다: {env_file}")
