#!/usr/bin/env python3
"""
Create a basic .env file with user-provided password and auto-generated JWT secret.

Usage:
    python create_env.py

Or via Makefile:
    make env
"""

import getpass
import os
import secrets
import sys
from pathlib import Path

import bcrypt


def create_env():
    """Create a .env file with user input and auto-generated values."""
    env_path = Path(__file__).parent.parent.parent / ".env"

    print("=" * 60)
    print("ChitChats Environment Setup")
    print("=" * 60)
    print()

    # Check if .env already exists
    if env_path.exists():
        print(f"Warning: .env file already exists at {env_path}")
        overwrite = input("Overwrite? (y/N): ")
        if overwrite.lower() != "y":
            print("Aborted.")
            return False
        print()

    # Get username
    default_username = os.environ.get("USER", "User")
    username = input(f"Enter your display name [{default_username}]: ").strip()
    if not username:
        username = default_username

    # Get password
    print()
    while True:
        password = getpass.getpass("Enter your password: ")
        password_confirm = getpass.getpass("Confirm password: ")

        if password != password_confirm:
            print("\n  Passwords do not match. Please try again.\n")
            continue

        if len(password) < 4:
            print("\n  Password must be at least 4 characters.\n")
            continue

        break

    # Generate bcrypt hash
    salt = bcrypt.gensalt()
    password_hash = bcrypt.hashpw(password.encode("utf-8"), salt).decode("utf-8")

    # Generate JWT secret
    jwt_secret = secrets.token_hex(32)

    # Create .env content
    env_content = f"""# ChitChats Environment Configuration
# Generated by: make env

# User Configuration
USER_NAME={username}

# Authentication
# Password hash (generated from your password)
API_KEY_HASH={password_hash}

# JWT Secret (auto-generated)
JWT_SECRET={jwt_secret}

# Database Configuration
# SQLite (default for easy setup)
USE_SQLITE=true
# Uncomment below to use PostgreSQL instead:
# DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/chitchats

# Claude SDK Configuration
CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK=true

# Optional: Store password for test scripts (not recommended for production)
# CHITCHATS_PASSWORD={password}

# Debug mode (set to true for verbose logging)
DEBUG_AGENTS=false

# CORS - Frontend URL (update for production)
# FRONTEND_URL=https://your-app.vercel.app
"""

    # Write .env file
    env_path.write_text(env_content)

    print()
    print("=" * 60)
    print("Environment file created successfully!")
    print("=" * 60)
    print()
    print(f"  Location: {env_path}")
    print(f"  Username: {username}")
    print(f"  JWT Secret: {jwt_secret[:16]}...")
    print()
    print("Next steps:")
    print("  1. Run the app: make dev")
    print("     (SQLite database will be created automatically)")
    print()
    print("  For PostgreSQL instead, edit .env:")
    print("     - Comment out USE_SQLITE=true")
    print("     - Uncomment DATABASE_URL=...")
    print()

    return True


if __name__ == "__main__":
    try:
        success = create_env()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\nAborted.")
        sys.exit(1)
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)
